/**
 * apps/mobile/src/db/migrations.ts
 *
 * Re-exports the Drizzle migration bundle generated by:
 *   cd packages/db && npx drizzle-kit generate
 *
 * The expo driver generates packages/db/drizzle/migrations.js which imports:
 *   - meta/_journal.json  (migration manifest)
 *   - *.sql files         (inlined as strings via babel-plugin-inline-import)
 *
 * This module is consumed by useMigrations() from drizzle-orm/expo-sqlite/migrator
 * in useHandwritingDb.ts. Drizzle applies any pending migrations on first run.
 *
 * DO NOT edit this file manually. Re-run drizzle-kit generate after schema changes.
 */

import migrations from '../../../../packages/db/drizzle/migrations.js';
export default migrations;
